(defun agt-get-language-name (language-code)
  (catch 'break
	(maphash (lambda (name code)
			   (when (equal code language-code)
				 (throw 'break name)))
			 agt-available-languages)))

;; Name list is in reverse sort.
(defun agt-get-language-names ()
  (let (names)
	(maphash
	 (lambda (name code) (setq names (cons name names)))
	 agt-available-languages)
	names))

(defun agt-get-language-code (language-name)
  (gethash language-name agt-available-languages))

(defun agt-available-language-code (lang-code)
  (and lang-code (agt-get-language-name lang-code)))

;; Is hash-table the correct data-type to use for a lookup table that is constant?
(defvar agt-available-languages
  (let ((table (make-hash-table :test 'equal)))
    (mapcar
	 (lambda (pair)
	   (puthash (car pair) (cadr pair) table))
	 '(("Afrikaans" "af")
	   ("Albanian" "sq")
	   ("Amharic" "am")
	   ("Arabic" "ar")
	   ("Armenian" "hy")
	   ("Azerbaijani" "az")
	   ("Basque" "eu")
	   ("Belarusian" "be")
	   ("Bengali" "bn")
	   ("Bihari" "bh")
	   ("Breton" "br")
	   ("Bulgarian" "bg")
	   ("Burmese" "my")
	   ("Catalan" "ca")
	   ("Cherokee" "chr")
	   ("Chinese" "zh")
	   ("Chinese_SIMPLIFIED" "zh-CN")
	   ("Chinese_TRADITIONAL" "zh-TW")
	   ("Corsican" "co")
	   ("Croatian" "hr")
	   ("Czech" "cs")
	   ("Danish" "da")
	   ("Dhivehi" "dv")
	   ("Dutch" "nl")
	   ("English" "en")
	   ("Esperanto" "eo")
	   ("Estonian" "et")
	   ("Faroese" "fo")
	   ("Filipino" "tl")
	   ("Finnish" "fi")
	   ("French" "fr")
	   ("Frisian" "fy")
	   ("Galician" "gl")
	   ("Georgian" "ka")
	   ("German" "de")
	   ("Greek" "el")
	   ("Gujarati" "gu")
	   ("Haitian_CREOLE" "ht")
	   ("Hebrew" "iw")
	   ("Hindi" "hi")
	   ("Hungarian" "hu")
	   ("Icelandic" "is")
	   ("Indonesian" "id")
	   ("Inuktitut" "iu")
	   ("Irish" "ga")
	   ("Italian" "it")
	   ("Japanese" "ja")
	   ("Javanese" "jw")
	   ("Kannada" "kn")
	   ("Kazakh" "kk")
	   ("Khmer" "km")
	   ("Korean" "ko")
	   ("Kurdish" "ku")
	   ("Kyrgyz" "ky")
	   ("Lao" "lo")
	   ("Latin" "la")
	   ("Latvian" "lv")
	   ("Lithuanian" "lt")
	   ("Luxembourgish" "lb")
	   ("Macedonian" "mk")
	   ("Malay" "ms")
	   ("Malayalam" "ml")
	   ("Maltese" "mt")
	   ("Maori" "mi")
	   ("Marathi" "mr")
	   ("Mongolian" "mn")
	   ("Nepali" "ne")
	   ("Norwegian" "no")
	   ("Occitan" "oc")
	   ("Oriya" "or")
	   ("Pashto" "ps")
	   ("Persian" "fa")
	   ("Polish" "pl")
	   ("Portuguese" "pt")
	   ("Portuguese_portugal" "pt-PT")
	   ("Punjabi" "pa")
	   ("Quechua" "qu")
	   ("Romanian" "ro")
	   ("Russian" "ru")
	   ("Sanskrit" "sa")
	   ("Scots_gaelic" "gd")
	   ("Serbian" "sr")
	   ("Sindhi" "sd")
	   ("Sinhalese" "si")
	   ("Slovak" "sk")
	   ("Slovenian" "sl")
	   ("Spanish" "es")
	   ("Sundanese" "su")
	   ("Swahili" "sw")
	   ("Swedish" "sv")
	   ("Syriac" "syr")
	   ("Tajik" "tg")
	   ("Tamil" "ta")
	   ("Tatar" "tt")
	   ("Telugu" "te")
	   ("Thai" "th")
	   ("Tibetan" "bo")
	   ("Tonga" "to")
	   ("Turkish" "tr")
	   ("Ukrainian" "uk")
	   ("Urdu" "ur")
	   ("Uzbek" "uz")
	   ("Uighur" "ug")
	   ("Vietnamese" "vi")
	   ("Welsh" "cy")
	   ("Yiddish" "yi")
	   ("Yoruba" "yo")
	   ("Unknown" "")))
	table))

(provide 'arvid-google-translate-languages)
